# üè´ Previs√£o de Evas√£o Escolar durante Ensino M√©dio
## üìö Importando bibliotecas que ser√£o utilizadas

In [1]:
import pandas as pd

C:\Users\gabri\AppData\Local\Temp\ipykernel_9724\4080736814.py:1: DeprecationWarning:
Pyarrow will become a required dependency of pandas in the next major release of pandas (pandas 3.0),
(to allow more performant data types, such as the Arrow string type, and better interoperability with other libraries)
but was not found to be installed on your system.
If this would cause problems for you,
please provide us feedback at https://github.com/pandas-dev/pandas/issues/54466

  import pandas as pd

## üìñ Lendo os arquivos csv
### `rend_escolas_2020` e `rend_escolas_2022`: 
- Convertendo aquivo no formato 'xlsx' para 'csv'

In [2]:
read_file_rend_escolas_2020 = pd.read_excel('dados/tx_rend_escolas_2020.xlsx')
read_file_rend_escolas_2020.to_csv('dados/rend_escolas_2020.csv')
rend_escolas_2020_df = pd.DataFrame(pd.read_csv('dados/rend_escolas_2020.csv'))
rend_escolas_2020_df

C:\Users\gabri\AppData\Local\Temp\ipykernel_9724\1193156925.py:3: DtypeWarning: Columns (1,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  rend_escolas_2020_df = pd.DataFrame(pd.read_csv('dados/rend_escolas_2020.csv'))

,Unnamed: 0.1,Unnamed: 0,Minist√©rio da Educa√ß√£o,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,0,NaN,Instituto Nacional de Estudos e Pesquisas Educ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"Taxas de Rendimento Escolar (Aprova√ß√£o, Reprov...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Ano,Regi√£o,UF,C√≥digo do Munic√≠pio,Nome do Munic√≠pio,C√≥digo da Escola,Nome da Escola,Localiza√ß√£o,Depend√™ncia Administrativa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
131234,131234,2020,Centro-Oeste,DF,5300108.0,Bras√≠lia,53084055.0,COL MAPA,Urbana,Privada,...,--,--,--,--,--,--,--,--,--,--
131235,131235,2020,Centro-Oeste,DF,5300108.0,Bras√≠lia,53085000.0,COBIAN - COL BIANGULO,Urbana,Privada,...,--,--,--,--,--,--,--,--,--,--
131236,131236,2020,Centro-Oeste,DF,5300108.0,Bras√≠lia,53086007.0,CED VITORIA REGIA,Urbana,Privada,...,--,--,0,4,0,0,0,0,--,--
131237,131237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
131238,131238,Fonte: Censo da Educa√ß√£o B√°sica 2020/INEP.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [3]:
read_file_rend_escolas_2022 = pd.read_excel('dados/tx_rend_escolas_2022.xlsx')
read_file_rend_escolas_2022.to_csv('dados/rend_escolas_2022.csv')
rend_escolas_2022_df = pd.DataFrame(pd.read_csv('dados/rend_escolas_2022.csv'))
rend_escolas_2022_df

C:\Users\gabri\AppData\Local\Temp\ipykernel_9724\19349765.py:3: DtypeWarning: Columns (1,4,6) have mixed types. Specify dtype option on import or set low_memory=False.
  rend_escolas_2022_df = pd.DataFrame(pd.read_csv('dados/rend_escolas_2022.csv'))

,Unnamed: 0.1,Unnamed: 0,Minist√©rio da Educa√ß√£o,Unnamed: 2,Unnamed: 3,Unnamed: 4,Unnamed: 5,Unnamed: 6,Unnamed: 7,Unnamed: 8,...,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62
0,0,NaN,Instituto Nacional de Estudos e Pesquisas Educ...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,"Taxas de Rendimento Escolar (Aprova√ß√£o, Reprov...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,Ano,Regi√£o,UF,C√≥digo do Munic√≠pio,Nome do Munic√≠pio,C√≥digo da Escola,Nome da Escola,Localiza√ß√£o,Depend√™ncia Administrativa,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
129312,129312,2022,Centro-Oeste,DF,5300108.0,Bras√≠lia,53084055.0,COL MAPA,Urbana,Privada,...,0,0,0,0,0,0,0,0,--,--
129313,129313,2022,Centro-Oeste,DF,5300108.0,Bras√≠lia,53085000.0,COBIAN - COL BIANGULO,Urbana,Privada,...,--,--,--,--,--,--,--,--,--,--
129314,129314,2022,Centro-Oeste,DF,5300108.0,Bras√≠lia,53086007.0,CED VITORIA REGIA,Urbana,Privada,...,--,--,--,0,0.6,1.8,0,0,--,--
129315,129315,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
129316,129316,Fonte: Censo da Educa√ß√£o B√°sica 2022/INEP.,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

## ü´ß Limpeza dos dados 
### 1. `rend_escolas_2022`:
1.1. Remo√ß√£o de coluna extra de √≠ndice.

1.2. Altera√ß√£o na nomeclatura das colunas.

1.3. Remo√ß√£o das primeiras e √∫ltimas linhas indesejadas.

1.4. Reseta√ß√£o de √≠ndices.

1.5. Retirada do ponto e retorno da parte anterior ao ponto no c√≥digo das escolas, para ficar no mesmo modelo os dois dataframes.

1.6. Sele√ß√£o das colunas necess√°rias.

1.7. Renomea√ß√£o das colunas.

### 2. `microdados_ed_basica_2023`:
2.1. Transforma√ß√£o da coluna de c√≥digos das escolas em string para se igualar ao outro dataframe. 

2.2. Selec√£o das colunas necess√°rias.

2.3. Renomea√ß√£o das colunas.

2.4. Substitui√ß√£o de d√≠gitos pelos dados referentes.

### 3. Verifica√ß√£o se h√° c√≥digos de escolas duplicadas

In [4]:
rend_escolas_2020_df = rend_escolas_2020_df.drop(columns=['Unnamed: 0.1']) 
rend_escolas_2020_df.columns = rend_escolas_2020_df.iloc[7].values 
rend_escolas_2020_df = rend_escolas_2020_df.drop(rend_escolas_2020_df.index[:8]) 
rend_escolas_2020_df = rend_escolas_2020_df.drop(rend_escolas_2020_df.index[-2:])
rend_escolas_2020_df.reset_index(drop=True, inplace=True) 
rend_escolas_2020_df['CO_ENTIDADE'] = rend_escolas_2020_df['CO_ENTIDADE'].astype(str).str.partition('.')[0] 
rend_escolas_2020_df = rend_escolas_2020_df[['NO_MUNICIPIO', 'CO_ENTIDADE', 'TIPOLOCA', 'Dependad', 'tap_FUN', 'tap_MED', 'tre_FUN', 'tre_MED', 'tab_FUN', 'tab_MED']] 
rend_escolas_2020_df = rend_escolas_2020_df.rename(columns={'NO_MUNICIPIO':'municipio',
                                                    'CO_ENTIDADE':'codigo_escola',
                                                    'TIPOLOCA':'zona_de_localizacao', 
                                                    'Dependad':'dependencia_administrativa',
                                                    'tap_FUN':'total_de_aprovacao_ensino_fundamental',
                                                    'tap_MED':'total_de_aprovacao_ensino_medio',
                                                    'tre_FUN':'total_de_reprovacao_ensino_fundamental',
                                                    'tre_MED':'total_de_reprovacao_ensino_medio',
                                                    'tab_FUN':'taxa_de_abandono_ensino_fundamental',
                                                    'tab_MED':'taxa_de_abandono_ensino_medio'}) 
rend_escolas_2020_df

,municipio,codigo_escola,zona_de_localizacao,dependencia_administrativa,total_de_aprovacao_ensino_fundamental,total_de_aprovacao_ensino_medio,total_de_reprovacao_ensino_fundamental,total_de_reprovacao_ensino_medio,taxa_de_abandono_ensino_fundamental,taxa_de_abandono_ensino_medio
0,Alta Floresta D'Oeste,11022558,Rural,Estadual,0,--,0,--,100,--
1,Alta Floresta D'Oeste,11024291,Rural,Municipal,100,--,0,--,0,--
2,Alta Floresta D'Oeste,11024372,Urbana,Municipal,94.9,--,0,--,5.1,--
3,Alta Floresta D'Oeste,11024666,Rural,Municipal,99.4,--,0,--,0.6,--
4,Alta Floresta D'Oeste,11024682,Urbana,Estadual,99.8,99.3,0.2,0.7,0,0
...,...,...,...,...,...,...,...,...,...,...
131224,Bras√≠lia,53084020,Urbana,Privada,98.4,--,0,--,1.6,--
131225,Bras√≠lia,53084039,Urbana,Privada,99.1,--,0,--,0.9,--
131226,Bras√≠lia,53084055,Urbana,Privada,--,--,--,--,--,--
131227,Bras√≠lia,53085000,Urbana,Privada,100,--,0,--,0,--
131228,Bras√≠lia,53086007,Urbana,Privada,97.6,98.3,0,1.7,2.4,0

In [5]:
rend_escolas_2022_df = rend_escolas_2022_df.drop(columns=['Unnamed: 0.1']) 
rend_escolas_2022_df.columns = rend_escolas_2022_df.iloc[7].values 
rend_escolas_2022_df = rend_escolas_2022_df.drop(rend_escolas_2022_df.index[:8]) 
rend_escolas_2022_df = rend_escolas_2022_df.drop(rend_escolas_2022_df.index[-2:])
rend_escolas_2022_df.reset_index(drop=True, inplace=True) 
rend_escolas_2022_df['CO_ENTIDADE'] = rend_escolas_2022_df['CO_ENTIDADE'].astype(str).str.partition('.')[0] 
rend_escolas_2022_df = rend_escolas_2022_df[['NO_MUNICIPIO', 'CO_ENTIDADE', 'NO_CATEGORIA', 'NO_DEPENDENCIA', '1_CAT_FUN', '1_CAT_MED', '2_CAT_FUN', '2_CAT_MED', '3_CAT_FUN', '3_CAT_MED']] 
rend_escolas_2022_df = rend_escolas_2022_df.rename(columns={'NO_MUNICIPIO':'municipio',
                                                    'CO_ENTIDADE':'codigo_escola',
                                                    'NO_CATEGORIA':'zona_de_localizacao', 
                                                    'NO_DEPENDENCIA':'dependencia_administrativa',
                                                    '1_CAT_FUN':'total_de_aprovacao_ensino_fundamental',
                                                    '1_CAT_MED':'total_de_aprovacao_ensino_medio',
                                                    '2_CAT_FUN':'total_de_reprovacao_ensino_fundamental',
                                                    '2_CAT_MED':'total_de_reprovacao_ensino_medio',
                                                    '3_CAT_FUN':'taxa_de_abandono_ensino_fundamental',
                                                    '3_CAT_MED':'taxa_de_abandono_ensino_medio'}) 
rend_escolas_2022_df

,municipio,codigo_escola,zona_de_localizacao,dependencia_administrativa,total_de_aprovacao_ensino_fundamental,total_de_aprovacao_ensino_medio,total_de_reprovacao_ensino_fundamental,total_de_reprovacao_ensino_medio,taxa_de_abandono_ensino_fundamental,taxa_de_abandono_ensino_medio
0,Alta Floresta D'Oeste,11022558,Rural,Estadual,100,--,0,--,0,--
1,Alta Floresta D'Oeste,11024291,Rural,Municipal,88.9,--,11.1,--,0,--
2,Alta Floresta D'Oeste,11024372,Urbana,Municipal,88.2,--,11.8,--,0,--
3,Alta Floresta D'Oeste,11024666,Rural,Municipal,96.2,--,3.8,--,0,--
4,Alta Floresta D'Oeste,11024682,Urbana,Estadual,93,91.3,6.3,0.3,0.7,8.4
...,...,...,...,...,...,...,...,...,...,...
129302,Bras√≠lia,53084020,Urbana,Privada,100,--,0,--,0,--
129303,Bras√≠lia,53084039,Urbana,Privada,100,--,0,--,0,--
129304,Bras√≠lia,53084055,Urbana,Privada,99.6,100,0.4,0,0,0
129305,Bras√≠lia,53085000,Urbana,Privada,100,--,0,--,0,--
129306,Bras√≠lia,53086007,Urbana,Privada,85.7,93.6,14.3,5.8,0,0.6

In [6]:
print(rend_escolas_2020_df['codigo_escola'].duplicated().sum())
print(rend_escolas_2022_df['codigo_escola'].duplicated().sum())

0
0

In [7]:
rend_escolas_2020_df.to_csv('dados/rend_escolas_manipulados_2020.csv')
rend_escolas_2022_df.to_csv('dados/rend_escolas_manipulados_2022.csv')